# Generated by Django 3.2.8 on 2021-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211026_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_from', models.IntegerField()),
                ('amount_to', models.IntegerField()),
                ('discount_from', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount_to', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
