# Generated by Django 3.2.8 on 2022-02-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qu_id', models.AutoField(primary_key=True, serialize=False)),
                ('qu_text', models.CharField(max_length=100)),
                ('qu_type', models.CharField(choices=[('C', 'Closed end question'), ('O', 'Open end question')], max_length=25)),
                ('qu_class', models.CharField(choices=[('B', 'Chatbot review'), ('W', 'Website review')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('txt_res_id', models.AutoField(primary_key=True, serialize=False)),
                ('txt_res_date', models.DateField()),
                ('txt_res_text', models.CharField(max_length=200)),
                ('txt_res_sentiment', models.CharField(max_length=50)),
                ('qu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='QuestionText', to='sentiment.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
                ('op_text', models.CharField(max_length=50)),
                ('qu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='sentiment.question')),
            ],
        ),
        migrations.CreateModel(
            name='OptionResponse',
            fields=[
                ('op_res_id', models.AutoField(primary_key=True, serialize=False)),
                ('op_res_date', models.DateField()),
                ('op_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Option', to='sentiment.questionoptions')),
            ],
        ),
    ]
