# Generated by Django 3.2.8 on 2022-02-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionresponse',
            name='op_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Option', to='sentiment.questionoptions'),
        ),
        migrations.AlterField(
            model_name='questionoptions',
            name='qu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='sentiment.question'),
        ),
    ]
