# Generated by Django 3.2.8 on 2022-02-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_auto_20220219_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoptions',
            name='qu_act_status',
            field=models.BooleanField(default=True),
        ),
    ]
