# Generated by Django 3.2.8 on 2022-02-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0005_questionoptions_qu_act_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoptions',
            name='qu_act_status',
        ),
        migrations.AddField(
            model_name='question',
            name='qu_act_status',
            field=models.BooleanField(default=True),
        ),
    ]
