# Generated by Django 3.2.8 on 2022-02-23 01:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0006_auto_20220220_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionresponse',
            name='op_res_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='textresponse',
            name='qu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuestionText', to='sentiment.question'),
        ),
        migrations.AlterField(
            model_name='textresponse',
            name='txt_res_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
